[workspace]
authors = ["Stephen Cross <stephencross86@gmail.com>"]
channels = ["conda-forge","anaconda"]
channel-priority = "disabled"
name = "deep-learning-models"
platforms = ["win-64", "linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.7,<3.8"

[pypi-dependencies]
h5py = "==2.10.0"
imageio = ">=2.31.2,<3"
protobuf = ">=3.20.0,<4"
scipy = ">=1.7.3,<2"
tensorflow = "==1.15.0"
tensorflow-gpu = "==1.15.0"
numpy = ">=1.21.6,<2"


