[workspace]
authors = ["Stephen Cross <stephencross86@gmail.com>"]
channels = ["conda-forge"]
name = "deep-learning-models"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.7,<3.8"

[pypi-dependencies]
tensorflow = "==1.15.0"
six = "*"
imageio = ">=2.31.2, <3"
protobuf = ">=3.20.0, <4"
scipy = ">=1.7.3, <2"
